
import java.awt.List;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.*;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows 10
 */
public class Bill extends javax.swing.JFrame {

    
    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
        jLabel3.setIcon(new ImageIcon("src\\photocar\\bill2.png"));
    }

        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    /*public static void readfile(String[] args) throws IOException{
    
       File Filename = new File("src\\Information\\"+".txt");

    
    }*/
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        name = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 299, 635));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 40, 131, -1));
        getContentPane().add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 78, 131, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ชื่อ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("นามสกุล");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 78, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 127, -1, -1));

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 614, 70, 32));

        jButton3.setText("cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 614, 86, 32));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
        String name1 = name.getText();
        String surname1 = surname.getText();
        
        String nameandsurname = name1 +" "+surname1;
        
        //System.out.print(nameandsurname);
        
       /* 
        File Filename = new File("src\\Information\\"+nameandsurname+".txt");
        
        try {
                FileReader Files = new FileReader("src\\Information\\"+nameandsurname+".txt");
                Path wiki_path = Paths.get("src\\Information\\"+nameandsurname+".txt");
                

                List<String> Lines = Files.readAllLines((nameandsurname+".txt"));
            
        } catch (FileNotFoundException ex) {
            
            
            
            Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
        }catch (IOException e) {
            System.out.println(e);
        }
        */////////////////////
        
        try {
            BufferedReader r = new  BufferedReader(new FileReader("src\\Information\\"+nameandsurname+".txt"));            
            String[] bills = new String[9];        
            for(int a = 0 ; a < bills.length ; a++ )
            {
                
                bills[a] = r.readLine(); 
                System.out.println(bills[a]);
                
            }
       
            
            
            jTextArea1.append("       ╔══════════════════╗\n");
            jTextArea1.append("                          Car Shop \n");
            jTextArea1.append("  ¸¸.•*´¨`*﻿ •.¸¸.•*´¨`*•.¸¸.•*´¨`*•.¸¸\n");
            jTextArea1.append(" ----------------------------------------------------\n");
            jTextArea1.append(" ----------------------------------------------------\n"); 
            jTextArea1.append("\n"+bills[7]+"");
            jTextArea1.append("\nName : "+bills[0]+"");
            jTextArea1.append("\nGender : "+bills[1]+"");
            jTextArea1.append("\nD-M-Y : "+bills[2]+"");
            jTextArea1.append("\nAddress : "+bills[3]+"");
            jTextArea1.append("\nID :"+bills[4]+"");
            jTextArea1.append("\nNumber : "+bills[5]+"");
            jTextArea1.append("\nE-mail : "+bills[6]+"");
            jTextArea1.append("\nPay : "+bills[8]+"");
            
            jTextArea1.append( "\n*********************************\n");
            jTextArea1.append( "\n");
            jTextArea1.append("            THANK YOU VERY MUCH\n");
            jTextArea1.append( "\n");
            jTextArea1.append("\n");
            jTextArea1.append( "•❁•❁•❁•❁•❁•❁•❁•❁•❁•❁•❁•❁•❁•\n");
            jTextArea1.append("\n");
            jTextArea1.append("       ╚══════════════════╝\n");
            jTextArea1.append("\n");
            
            r.close();
        } catch (FileNotFoundException ex) {
            
            Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            
            Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        

        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            jTextArea1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField surname;
    // End of variables declaration//GEN-END:variables
}
